# WEBTREES DOCKER COMPOSE
#
# start   http://localhost:10080
# default user: admin / changethepassword
#

version: '2'
services:

  webtrees:
    image:  cutyno/webtrees:latest
    container_name:  webtrees
    links:
      - webtrees-database:webtrees-database
    ports:
      - "10080:80"
    depends_on:
      - webtrees-database
      - webtrees-data-volumes
    volumes_from: 
      - webtrees-data-volumes
       
  webtrees-database:
    image: cutyno/webtrees-database
    container_name:   webtrees-database
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=mustnotchange
      - MYSQL_DATABASE=webtrees
      - MYSQL_USER=webtrees
      - MYSQL_PASSWORD=mustnotchange
    command: --default-authentication-plugin=mysql_native_password
    volumes_from: 
      - webtrees-data-volumes
    depends_on:
      - webtrees-data-volumes

  webtrees-data-volumes:
    image: busybox
    container_name: webtrees-data-volumes
    volumes:
      - ./webtrees/var/lib/mysql:/var/lib/mysql
      - ./webtrees/var/www/html/webtrees/data:/var/www/html/webtrees/data
